version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  api:
    build: .
    env_file: .env
    command: bash -c "alembic upgrade head &&  uvicorn main:app --port=8000 --host=0.0.0.0 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db